name: Build Docker Image

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine Environment
        id: determine_environment
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            if [[ ${{ github.event.pull_request.base.ref }} == *'dev'* && ${{ github.event.pull_request.head.ref }} == *'main'* ]]; then
              echo "env=dev" >> $GITHUB_ENV
            elif [[ ${{ github.event.pull_request.base.ref }} == *'stage'* && ${{ github.event.pull_request.head.ref }} == *'main'* ]]; then
              echo "env=stage" >> $GITHUB_ENV
            elif [[ ${{ github.event.pull_request.base.ref }} == *'uat'* && ${{ github.event.pull_request.head.ref }} == *'main'* ]]; then
              echo "env=uat" >> $GITHUB_ENV
            elif [[ ${{ github.event.pull_request.base.ref }} == *'prod'* && ${{ github.event.pull_request.head.ref }} == *'main'* ]]; then
              echo "env=prod" >> $GITHUB_ENV
            else
              echo "env=unknown" >> $GITHUB_ENV
            fi
          else
            echo "env=unknown" >> $GITHUB_ENV
          fi

      - name: Set Environment Output
        id: set_env
        run: echo "env=${{ steps.determine_environment.outputs.env }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          echo "Building Docker image for ${{ env }} environment..."
          # docker build -t your-docker-image:$GITHUB_SHA .
