name: Build and Push Docker Image - prod

on:
  pull_request:
    types:
      - closed
    branches:
      - prod

jobs:
  build_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Publish Solution
        run: |
          cd netcore
          dotnet publish -c Release

      - name: Build Docker Image - prod
        run: |
          echo "Building Docker image for prod environment"
          
          # Generate a unique tag using the pull request number and GitHub SHA
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          TAG="prod-pr-${PR_NUMBER}-${GITHUB_SHA}"

          # Navigate to the netcore folder
          cd netcore

          # Build the Docker image with the generated tag
          docker build -t dotnetapp:$TAG .
  
  push_prod:
    runs-on: ubuntu-latest

    needs: build_prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push Docker Image - prod
        run: |
          echo "Pushing Docker image for prod environment"
          # docker login -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_PASSWORD your-artifactory-registry
          # docker push your-artifactory-registry/your-docker-image:prod-$GITHUB_SHA
