name: Push Docker Image to Artifactory

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine Environment
        id: determine_environment
        run: echo "env=${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.name, 'dev') && 'dev' || github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.name, 'stage') && 'stage' || github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.name, 'uat') && 'uat' || github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.name, 'prod') && 'prod' || 'unknown'}}" >> $GITHUB_ENV

      - name: Set Environment Output
        id: set_env
        run: echo "env=${{ steps.determine_environment.outputs.env }}" >> $GITHUB_ENV

      - name: Push Docker Image to Artifactory
        run: |
          echo "Pushing Docker image to Artifactory for ${{ env }} environment..."
          # docker tag your-docker-image:$GITHUB_SHA your-artifactory-registry/your-docker-image:$GITHUB_SHA
          # docker login -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_PASSWORD your-artifactory-registry
          # docker push your-artifactory-registry/your-docker-image:$GITHUB_SHA
