name: Build and Push Docker Image - uat

on:
  pull_request:
    types:
      - closed
    branches:
      - uat

jobs:
  build_uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Publish Solution
        run: |
          cd netcore
          dotnet publish -c Release

      - name: Build Docker Image - uat
        run: |
          echo "Building Docker image for uat environment"
          
          # Generate a unique tag using the pull request number and GitHub SHA
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          TAG="uat-pr-${PR_NUMBER}-${GITHUB_SHA}"

          # Navigate to the netcore folder
          cd netcore

          # Build the Docker image with the generated tag
          docker build -t dotnetapp:$TAG .
  
  push_uat:
    runs-on: ubuntu-latest

    needs: build_uat

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push Docker Image - uat
        run: |
          echo "Pushing Docker image for uat environment"
          # docker login -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_PASSWORD your-artifactory-registry
          # docker push your-artifactory-registry/your-docker-image:uat-$GITHUB_SHA
